### PR TITLE
If anyone wants compatibility with the latest python versions, I made a fork

### PR DESCRIPTION
**Pull request by unexploredtest**
This isn't meant to be a PR, so sorry for making one, but I didn't find another way to notify anyone who might be interested. As you may know, the current repository is made to work with python 2.7, which is old and incompatible. I tried searching for one which was compatible with the latest version but no luck(Michal Daniel Dobrzanski isn't the one I was looking for), so I decided to make one:
https://github.com/unexploredtest/neural-networks-and-deep-learning
Hopefully somebody will find it useful.

### CODE REVIEW

**Comment by FranklinChen** [comment]
How does this differ from the already existing https://github.com/MichalDanielDobrzanski/DeepLearningPython mentioned in the README?

**Comment by arun-r80** [comment]
This will be helpful for me, Thanks a lot

**Comment by francescoboc** [comment]
Thank you very much, this saved me so much time!!

**Comment by eitah** [comment]
Thank you this is great!!
Could we add this to the readme in addition to the 3.10

**Comment by mnielsen** [comment]
Thanks - I added a note to the Readme pointing to this branch.

**Pull request closed without merging**
